"""empty message

Revision ID: 835d3482e199
Revises: 2a8ecd8b5567
Create Date: 2020-12-07 00:04:57.960602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835d3482e199'
down_revision = '2a8ecd8b5567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
